load("@bazel_skylib//rules:common_settings.bzl", "string_flag")
load("@gazelle//:def.bzl", "gazelle")
load("@rules_go//go:def.bzl", "go_cross_binary")
load("@rules_img//img:image.bzl", "image_manifest")
load("@rules_img//img:layer.bzl", "file_metadata", "image_layer")
load("@rules_img//img:load.bzl", "image_load")
load("@rules_img//img:push.bzl", "image_push")

gazelle(name = "gazelle")

platform(
    name = "linux_amd64",
    constraint_values = [
        "@platforms//cpu:x86_64",
        "@platforms//os:linux",
    ],
)

genrule(
    name = "release_version",
    outs = ["release_version.txt"],
    cmd = "printf '%s\\n' '{}' > $@".format(module_version()),
)

go_cross_binary(
    name = "fast_linux_amd64",
    platform = "@rules_go//go/toolchain:linux_amd64",
    target = "//fast",
)

go_cross_binary(
    name = "fast_linux_arm64",
    platform = "@rules_go//go/toolchain:linux_arm64",
    target = "//fast",
)

go_cross_binary(
    name = "fast_darwin_amd64",
    platform = "@rules_go//go/toolchain:darwin_amd64",
    target = "//fast",
)

go_cross_binary(
    name = "fast_darwin_arm64",
    platform = "@rules_go//go/toolchain:darwin_arm64",
    target = "//fast",
)

image_layer(
    name = "installer_server_layer",
    srcs = {"/app/installer": "//installer:installer"},
    default_metadata = file_metadata(
        gid = 65532,
        mode = "0755",
        uid = 65532,
    ),
)

image_manifest(
    name = "installer_image",
    base = "@distroless_static",
    entrypoint = ["/app/installer"],
    layers = [":installer_server_layer"],
    platform = ":linux_amd64",
    user = "65532:65532",
)

image_load(
    name = "installer_image_load",
    image = ":installer_image",
    tag = "fast-installer:dev",
)

string_flag(
    name = "gar_registry",
    build_setting_default = "example-docker.pkg.dev",
)

string_flag(
    name = "gar_repository",
    build_setting_default = "example/fast-cli/fast-installer",
)

image_push(
    name = "installer_image_push",
    build_settings = {
        "REGISTRY": ":gar_registry",
        "REPOSITORY": ":gar_repository",
    },
    image = ":installer_image",
    registry = "{{.REGISTRY}}",
    repository = "{{.REPOSITORY}}",
    tag = "v" + module_version(),
)
