load("@gazelle//:def.bzl", "gazelle")
load("@rules_go//go:def.bzl", "go_cross_binary")

gazelle(name = "gazelle")

genrule(
    name = "release_version",
    outs = ["release_version.txt"],
    cmd = "printf '%s\\n' '{}' > $@".format(module_version()),
)

go_cross_binary(
    name = "fast_linux_amd64",
    platform = "@rules_go//go/toolchain:linux_amd64",
    target = "//cmd/fast",
)

go_cross_binary(
    name = "fast_linux_arm64",
    platform = "@rules_go//go/toolchain:linux_arm64",
    target = "//cmd/fast",
)

go_cross_binary(
    name = "fast_darwin_amd64",
    platform = "@rules_go//go/toolchain:darwin_amd64",
    target = "//cmd/fast",
)

go_cross_binary(
    name = "fast_darwin_arm64",
    platform = "@rules_go//go/toolchain:darwin_arm64",
    target = "//cmd/fast",
)
