#!/usr/bin/env python3
"""Prepare Bazel binaries and publish a tagged GitHub release."""

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path


REPOSITORY = "justinswe/fast-cli"
RELEASES = f"https://api.github.com/repos/{REPOSITORY}/releases"
ASSETS = {
    "fast_linux_amd64": "linux-amd64",
    "fast_linux_arm64": "linux-arm64",
    "fast_darwin_amd64": "darwin-amd64",
    "fast_darwin_arm64": "darwin-arm64",
}


def command(*args):
    """Return the stdout of a successful command."""
    return subprocess.check_output(args, text=True).strip()


def module_version(flags):
    """Read the version file generated by Bazel's module_version()."""
    paths = command("bazel", "cquery", *flags, "--output=files", "//:release_version").splitlines()
    if len(paths) != 1:
        raise ValueError(f"expected one release version output, got {paths}")
    version = Path(paths[0]).read_text().strip()
    if not re.fullmatch(r"\d+\.\d+\.\d+", version):
        raise ValueError("Bazel module version must be MAJOR.MINOR.PATCH")
    return version


def check_main(token):
    """Require HEAD to be GitHub's current main tip and return its SHA."""
    head = command("git", "rev-parse", "HEAD")
    ref = request("GET", f"https://api.github.com/repos/{REPOSITORY}/git/ref/heads/main", token)
    if ref is None or ref["object"]["sha"] != head:
        raise ValueError("HEAD is not the tip of main")
    return head


def prepare_assets(tag, flags):
    """Copy four built Bazel outputs into the release directory."""
    output = Path("dist")
    output.mkdir(exist_ok=True)
    checksums = []
    assets = []
    for target, platform in ASSETS.items():
        paths = command("bazel", "cquery", *flags, "--output=files", f"//:{target}").splitlines()
        if len(paths) != 1:
            raise ValueError(f"expected one output for {target}, got {paths}")
        name = f"fast-{tag}-{platform}"
        destination = output / name
        shutil.copyfile(paths[0], destination)
        destination.chmod(0o755)
        checksums.append(f"{hashlib.sha256(destination.read_bytes()).hexdigest()}  {name}")
        assets.append(destination)
    checksum_file = output / "SHA256SUMS"
    checksum_file.write_text("\n".join(checksums) + "\n")
    return assets + [checksum_file]


def request(method, url, token, body=None, content_type="application/json"):
    """Call the GitHub REST API and return its JSON response."""
    if isinstance(body, dict):
        body = json.dumps(body).encode()
    headers = {
        "Accept": "application/vnd.github+json",
        "Authorization": f"Bearer {token}",
        "X-GitHub-Api-Version": "2026-03-10",
    }
    if body is not None:
        headers["Content-Type"] = content_type
    call = urllib.request.Request(url, data=body, headers=headers, method=method)
    try:
        with urllib.request.urlopen(call, timeout=60) as response:
            return json.load(response)
    except urllib.error.HTTPError as error:
        if error.code == 404 and method == "GET":
            return None
        raise RuntimeError(f"GitHub {method} {url}: HTTP {error.code}") from None
    except urllib.error.URLError:
        raise RuntimeError(f"GitHub {method} {url}: request failed") from None


def publish_release(tag, commit, release, assets, token):
    """Upload missing assets to a draft tagged at commit, then publish the release."""
    if release is None:
        release = request("POST", RELEASES, token, {
            "tag_name": tag,
            "target_commitish": commit,
            "name": tag,
            "draft": True,
            "generate_release_notes": True,
        })

    release_id = release["id"]
    uploaded = request("GET", f"{RELEASES}/{release_id}/assets?per_page=100", token)
    by_name = {asset["name"]: asset for asset in uploaded}
    for asset in assets:
        data = asset.read_bytes()
        digest = "sha256:" + hashlib.sha256(data).hexdigest()
        if asset.name in by_name:
            if by_name[asset.name].get("digest") != digest:
                raise ValueError(f"existing asset {asset.name} has a different digest")
            continue
        upload_url = (
            f"https://uploads.github.com/repos/{REPOSITORY}/releases/{release_id}/assets"
            f"?name={urllib.parse.quote(asset.name)}"
        )
        request("POST", upload_url, token, data, "application/octet-stream")

    uploaded = request("GET", f"{RELEASES}/{release_id}/assets?per_page=100", token)
    by_name = {asset["name"]: asset for asset in uploaded}
    if set(by_name) != {asset.name for asset in assets}:
        raise ValueError("release assets did not match the expected files")
    for asset in assets:
        digest = "sha256:" + hashlib.sha256(asset.read_bytes()).hexdigest()
        if by_name[asset.name].get("digest") != digest:
            raise ValueError(f"release asset {asset.name} has a different digest")
    request("PATCH", f"{RELEASES}/{release_id}", token, {"draft": False})


def main():
    """Prepare local assets, optionally publishing from trusted CI."""
    parser = argparse.ArgumentParser()
    parser.add_argument("--publish", action="store_true")
    args = parser.parse_args()
    token = os.environ.pop("GITHUB_RELEASE_TOKEN", None)
    flags = ("--config=rbe", "--config=ci") if args.publish else ()
    tag = "v" + module_version(flags)
    if not args.publish:
        assets = prepare_assets(tag, flags)
        print("Prepared " + ", ".join(str(asset) for asset in assets))
        return
    if not token:
        raise ValueError("GITHUB_RELEASE_TOKEN is not configured")
    commit = check_main(token)
    release = request("GET", f"{RELEASES}/tags/{tag}", token)
    if release is not None and not release["draft"]:
        print(f"release {tag} already published; skipping")
        return
    assets = prepare_assets(tag, flags)
    publish_release(tag, commit, release, assets, token)
    print("Published " + ", ".join(str(asset) for asset in assets))


if __name__ == "__main__":
    try:
        main()
    except (ValueError, RuntimeError) as error:
        print(f"release: {error}", file=sys.stderr)
        raise SystemExit(1)
